version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge


services:
    ### PHP-FPM ##############################################
    phpfpm:
        build:
          context: ./phpfpm
          args:
            - RUN_USER_UID=${RUN_USER_UID}
            - RUN_USER_GID=${RUN_USER_GID}
            - http_proxy
            - https_proxy
            - no_proxy
        volumes:
          - ./phpfpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
          - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        expose:
          - "9000"
        networks:
          - backend
    
    php70fpm:
        build:
          context: ./php70fpm
          args:
            - RUN_USER_UID=${RUN_USER_UID}
            - RUN_USER_GID=${RUN_USER_GID}
            - http_proxy
            - https_proxy
            - no_proxy
        volumes:
          - ./phpini/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
          - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        expose:
          - "9000"
        networks:
          - backend

    nginx:
        build:
          context: ./nginx
          args:
            - RUN_USER_UID=${RUN_USER_UID}
            - RUN_USER_GID=${RUN_USER_GID}
            - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
            - PHP70_UPSTREAM_CONTAINER=${NGINX_PHP70_UPSTREAM_CONTAINER}
            - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
            - http_proxy
            - https_proxy
            - no_proxy
        volumes:
          - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
          - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
          - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
          - ${NGINX_SSL_PATH}:/etc/nginx/ssl
        ports:
          - "${NGINX_HOST_HTTP_PORT}:80"
          - "${NGINX_HOST_HTTPS_PORT}:443"
        depends_on:
          - phpfpm
        networks:
          - frontend
          - backend
